services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - kobi-net
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001/api

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    networks:
      - kobi-net
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env

  postgres:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    networks:
      - kobi-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "5672:5672" 
      - "15672:15672"
    networks:
      - kobi-net
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

networks:
  kobi-net:
    driver: bridge

volumes:
  pgdata: